POST http://localhost:64857/todos/createList
Content-Type: application/json

{
    "todo": {
        "todoListId"  : "abcd",
        "title"       : "first todo",
        "description" : "first todo",
        "status"      : "Open",
        "createdBy"   : "Amol",
        "createdAt"   : "2025-11-11T14:33:43.810Z",
        "updatedBy"   :  "Amol",
        "updatedAt"   : "2025-11-11T14:33:43.810Z"
    }
}

###

POST http://localhost:4004/todos/todolists
Content-Type: application/json

{
    "title": "test description",
    "description": "test description"
}

###
GET http://localhost:4004/todos/todolists('878ac2cf-f002-4cc7-8ae3-c792f281c4c3')?$expand=items

###
POST http://localhost:4004/todos/addItem
Content-Type: application/json

{
  "todoListId": "796096d4-484c-404b-8c79-ea0bab55bfe7",
  "title": "item 7",
  "description": "item 7"
}
